/* Measures where the sign actually sits inside each official image, so the UI
   can zoom past the white margin the source files carry. The files themselves
   are never modified — this only records a viewport.
   Run after adding or replacing images:   node tools/measure-signs.js        */
const fs = require('fs'), cp = require('child_process'), path = require('path');
const ROOT = path.join(__dirname, '..');
const DIR = path.join(ROOT, 'assets', 'signs');
const files = fs.readdirSync(DIR).filter(f => /\.(jpe?g|png)$/i.test(f)).sort();

const html = `<!doctype html><html><head><meta charset="utf-8"></head><body><pre id="out"></pre><script>
const FILES = ${JSON.stringify(files)};
const load = f => new Promise(res => { const i = new Image();
  i.onload = () => res([f, i]); i.onerror = () => res([f, null]); i.src = 'signs/' + f; });
Promise.all(FILES.map(load)).then(list => {
  const out = {}, c = document.createElement('canvas'), x = c.getContext('2d', {willReadFrequently:true});
  for (const [f, img] of list) {
    if (!img) { out[f] = null; continue; }
    c.width = img.naturalWidth; c.height = img.naturalHeight;
    x.drawImage(img, 0, 0);
    const d = x.getImageData(0, 0, c.width, c.height).data;
    let x0 = c.width, y0 = c.height, x1 = -1, y1 = -1;
    for (let py = 0; py < c.height; py++) for (let px = 0; px < c.width; px++) {
      const i = (py * c.width + px) * 4;
      /* anything that is not near-white counts as ink */
      if (d[i] < 244 || d[i+1] < 244 || d[i+2] < 244) {
        if (px < x0) x0 = px; if (px > x1) x1 = px;
        if (py < y0) y0 = py; if (py > y1) y1 = py;
      }
    }
    out[f] = (x1 < 0) ? null : { w: c.width, h: c.height,
      x: +(x0 / c.width).toFixed(4), y: +(y0 / c.height).toFixed(4),
      bw: +((x1 - x0 + 1) / c.width).toFixed(4), bh: +((y1 - y0 + 1) / c.height).toFixed(4) };
  }
  document.getElementById('out').textContent = JSON.stringify(out);
});
</` + `script></body></html>`;

const page = path.join(ROOT, 'assets', '_measure.html');
fs.writeFileSync(page, html);
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const dom = cp.execFileSync(CHROME, ['--headless=new','--disable-gpu','--allow-file-access-from-files',
  '--virtual-time-budget=25000','--window-size=400,400','--dump-dom','file://' + page],
  { maxBuffer: 1 << 28, stdio: ['ignore','pipe','ignore'] }).toString();
fs.unlinkSync(page);
const m = dom.match(/<pre id="out">([\s\S]*?)<\/pre>/);
if (!m) { console.error('measurement failed'); process.exit(1); }
const box = JSON.parse(m[1].replace(/&quot;/g,'"').replace(/&amp;/g,'&'));

const lines = ['/* ── Where the sign sits inside each official image ────────────────────────',
 '   GENERATED by tools/measure-signs.js — do not hand-edit.',
 '   x/y/bw/bh are fractions of the source image. The published files carry a lot',
 '   of white margin; the UI uses these to zoom to the sign itself rather than',
 '   cropping or re-encoding the artwork, which must stay unmodified.       */',
 'const SIGNBOX = {'];
let missing = 0;
Object.keys(box).sort().forEach(k => {
  const b = box[k];
  if (!b) { missing++; return; }
  lines.push(`  ${JSON.stringify(k)}:[${b.x},${b.y},${b.bw},${b.bh},${b.w},${b.h}],`);
});
lines.push('};', "if (typeof module !== 'undefined') module.exports = SIGNBOX;");
fs.writeFileSync(path.join(ROOT, 'src', 'signbox.js'), lines.join('\n') + '\n');
const vals = Object.values(box).filter(Boolean);
const avg = vals.reduce((a,b) => a + b.bw * b.bh, 0) / vals.length;
console.log(`measured ${vals.length} images (${missing} blank)`);
console.log(`sign fills on average ${(avg*100).toFixed(0)}% of the source image area`);
