/* Regenerates src/gbox.js — the measured ink bounds of every glyph.
   Run after changing any glyph geometry:   node tools/measure.js          */
const fs = require('fs'), cp = require('child_process'), path = require('path');
const ROOT = path.join(__dirname, '..');
const G = require(path.join(ROOT, 'src/glyphs.js'));
const ids = Object.keys(G);
const svgs = ids.map(id =>
  `<svg id="s_${id}" width="100" height="100" viewBox="0 0 100 100" style="position:absolute;left:0;top:0">` +
  `<g id="g_${id}" fill="#000">${G[id]}</g></svg>`).join('');
const script =
  `var ids=${JSON.stringify(ids)},r={};ids.forEach(function(id){` +
  `var s=document.getElementById("s_"+id),g=document.getElementById("g_"+id),` +
  `sr=s.getBoundingClientRect(),gr=g.getBoundingClientRect();` +
  `r[id]=[+(gr.left-sr.left).toFixed(2),+(gr.top-sr.top).toFixed(2),+gr.width.toFixed(2),+gr.height.toFixed(2)];});` +
  `document.getElementById("out").textContent=JSON.stringify(r);`;
const tmp = path.join(process.env.TMPDIR || '/tmp', 'g1-measure.html');
fs.writeFileSync(tmp, `<!doctype html><html><head><meta charset="utf-8"></head><body style="margin:0">${svgs}<pre id="out"></pre><script>${script}</` + `script></body></html>`);
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const dom = cp.execFileSync(CHROME, ['--headless=new','--disable-gpu','--virtual-time-budget=3000',
  '--window-size=600,600','--dump-dom','file://'+tmp], {maxBuffer: 1<<28, stdio:['ignore','pipe','ignore']}).toString();
const m = dom.match(/<pre id="out">([\s\S]*?)<\/pre>/);
if (!m) { console.error('measurement failed'); process.exit(1); }
const box = JSON.parse(m[1].replace(/&quot;/g,'"').replace(/&amp;/g,'&'));
const out = ['/* ── Measured visual bounds of every glyph ─────────────────────────────────',
 '   GENERATED by tools/measure.js — do not hand-edit. Each entry is the glyph\'s',
 '   real ink bounds [x, y, w, h] inside its 100x100 box, strokes included. The',
 '   renderer centres and scales every symbol from these, so a sign never depends',
 '   on how tightly its path happened to be drawn.                          */',
 'const GBOX = {'];
Object.keys(box).sort().forEach(k => { const b = box[k]; out.push(`  ${k}:[${b.join(',')}],`); });
out.push('};', "if (typeof module !== 'undefined') module.exports = GBOX;");
fs.writeFileSync(path.join(ROOT,'src/gbox.js'), out.join('\n')+'\n');
const off = Object.keys(box).filter(k=>{const b=box[k];return Math.max(Math.abs(b[0]+b[2]/2-50),Math.abs(b[1]+b[3]/2-50))>6;});
console.log('measured '+Object.keys(box).length+' glyphs; '+off.length+' off-centre in source (now corrected at render time)');
