BANK.push(
/* ══ POINTS & PENALTIES ═════════════════════════════════════════════════ */
{t:"penalties", q:"How long do demerit points stay on your record?", a:["1 year from the offence","2 years from the offence","3 years from the offence","Forever"], c:1,
 w:"Two years from the DATE OF THE OFFENCE, not the conviction."},
{t:"penalties", q:"A novice (G1/G2) driver gets a licence suspension at how many demerit points?", a:["6","9","12","15"], c:1,
 w:"9 points = 60-day suspension. A full licence holder gets to 15 first."},
{t:"penalties", q:"How long is a novice driver suspended at 9 demerit points?", a:["30 days","60 days","90 days","6 months"], c:1,
 w:"60 days, and you restart at 4 points afterwards."},
{t:"penalties", q:"A fully licensed driver is suspended at how many demerit points?", a:["9","12","15","20"], c:2,
 w:"15 points = 30-day suspension, then you restart at 7."},
{t:"penalties", q:"A novice driver gets their first warning letter at:", a:["2 points","6 points","9 points","15 points"], c:0,
 w:"Novice: 2 points warning, 6 points second letter, 9 points suspension."},
{t:"penalties", q:"Failing to remain at the scene of a collision costs:", a:["3 demerit points","4 demerit points","6 demerit points","7 demerit points"], c:3,
 w:"7 points — the maximum on the chart."},
{t:"penalties", q:"Careless driving costs how many demerit points?", a:["3","4","6","7"], c:2,
 w:"6 points, same as racing or failing to stop for a school bus."},
{t:"penalties", q:"Following too closely costs how many demerit points?", a:["2","3","4","6"], c:2,
 w:"4 points. Tailgating is treated as seriously as speeding 30-49 over."},
{t:"penalties", q:"Using a hand-held phone while driving costs a full licence holder:", a:["2 demerit points","3 demerit points","4 demerit points","6 demerit points"], c:1,
 w:"3 points on a first conviction, plus a fine and a 3-day suspension."},
{t:"penalties", q:"A NOVICE driver convicted of distracted driving receives:", a:["3 demerit points","No demerit points, but a 30-day suspension","A warning","6 demerit points"], c:1,
 w:"Novice drivers get suspensions instead: 30 days, then 90 days, then licence cancellation."},
{t:"penalties", q:"Failing to yield the right-of-way costs:", a:["2 demerit points","3 demerit points","4 demerit points","6 demerit points"], c:1,
 w:"3 points, same as disobeying a sign or signal."},
{t:"penalties", q:"Speeding 30 to 49 km/h over the limit costs:", a:["3 demerit points","4 demerit points","6 demerit points","7 demerit points"], c:1,
 w:"16-29 over is 3 points. 30-49 over is 4. Past that you are into stunt driving territory."},
{t:"penalties", q:"Opening your car door improperly into traffic costs:", a:["0 points","2 demerit points","3 demerit points","6 demerit points"], c:2,
 w:"3 points. Dooring badly injures cyclists."},
{t:"penalties", q:"Ontario's stunt driving threshold where the speed limit is UNDER 80 km/h is:", a:["20 km/h over","30 km/h over","40 km/h over","50 km/h over"], c:2,
 w:"40 over where the limit is under 80. 50 over where it is 80 or higher. Or any speed of 150+."},
{t:"penalties", q:"A stunt driving charge brings an immediate roadside:", a:["7-day suspension and 7-day impound","30-day suspension and 14-day vehicle impound","Fine only","90-day suspension"], c:1,
 w:"Before you ever see a courtroom. The car goes on a flatbed."},
{t:"penalties", q:"What is the 'warn range' for blood alcohol?", a:["0.00 to 0.05","0.05 to 0.08","0.08 to 0.10","Over 0.10"], c:1,
 w:"Not a criminal charge, but it still costs you your licence immediately."},
{t:"penalties", q:"Blowing over 0.08 or refusing a breath test brings an immediate:", a:["30-day suspension","60-day suspension","90-day suspension and 7-day vehicle impoundment","Warning"], c:2,
 w:"90 days off the road, car impounded 7 days, plus criminal charges."},
{t:"penalties", q:"A novice driver caught with ANY alcohol in their system faces:", a:["A warning","Impaired driving penalties plus additional fines","Nothing if under 0.05","A 1-day suspension"], c:1,
 w:"Zero means zero for novice drivers and everyone 21 and under."},
{t:"penalties", q:"Novice driver escalating sanctions follow this pattern:", a:["Warning, fine, suspension","30-day suspension, 90-day suspension, licence cancellation","Fine, fine, cancellation","60 days, then cancellation"], c:1,
 w:"Break your G1/G2 conditions three times and you leave the system entirely."},
{t:"penalties", q:"Which offence carries the SAME points as failing to remain at a collision?", a:["Careless driving","Failing to stop for police","Racing","Speeding 50+ over"], c:1,
 w:"Both are 7 points."},
{t:"penalties", q:"Not wearing a seatbelt, improper turns and driving too slowly all cost:", a:["2 demerit points","3 demerit points","4 demerit points","6 demerit points"], c:0,
 w:"The 2-point tier: belts, lights, signals, turns, slow driving, reversing on a highway."},
{t:"penalties", q:"Which of these is a 6-point offence?", a:["Following too closely","Failing to stop for a school bus","Speeding 20 over","Improper lane change"], c:1,
 w:"School bus, careless driving, racing, and speeding 50+ over are all 6."},
{t:"penalties", q:"A driver caught misusing an HOV lane receives:", a:["No points","2 demerit points","3 demerit points","6 demerit points"], c:2,
 w:"3 points, a ticket, and you must return to the general lanes at the next opening."},
{t:"penalties", q:"Using a radar detector in Ontario costs:", a:["Nothing, they are legal","2 demerit points","3 demerit points","6 demerit points"], c:2,
 w:"Radar detectors are illegal here — 3 points and the device is seized."},

/* ══ EFFICIENT / RESPONSIBLE DRIVING ════════════════════════════════════ */
{t:"along", q:"You should turn off your engine if parked for more than:", a:["10 seconds","1 minute","5 minutes","10 minutes"], c:0,
 w:"Restarting uses less fuel than idling past 10 seconds."},
{t:"emergencies", q:"Aggressive driving behaviours include:", a:["Signalling early","Tailgating, speeding and cutting in too closely","Keeping right","Checking mirrors"], c:1,
 w:"They also burn far more fuel than smooth driving."},
{t:"emergencies", q:"Someone else's driving annoys you. You should:", a:["Teach them a lesson","Flash your lights","Leave enforcement to the police","Follow them"], c:2,
 w:"Do not retaliate and do not take it personally. That is how road rage starts."}
);

/* ── late additions: details straight out of the two chapters ─────────── */
BANK.push(
{t:"parking", q:"The 'Dutch reach' means opening your driver's door with:", a:["Your left hand","Your right hand, which forces a shoulder check","Both hands","Your elbow"], c:1,
 w:"Reaching across turns your body — you end up looking for cyclists automatically."},
{t:"parking", q:"When you must open a door next to traffic you should:", a:["Open it fully and quickly","Keep it open only long enough to load or unload","Leave it open","Open it slowly and leave it"], c:1,
 w:"Every second that door is out in the lane is a second a cyclist can hit it."},
{t:"parking", q:"After parking you should:", a:["Leave the key in the ignition","Turn off the ignition and lights, remove the key and lock up","Leave the lights on","Leave the engine running"], c:1,
 w:"And never leave children or animals in the vehicle."},
{t:"parking", q:"Before pulling out of a parking spot you must:", a:["Just go","Signal and check for traffic","Sound your horn","Reverse first"], c:1,
 w:"Pulling out is a lane change from a standing start."},
{t:"intersections", q:"A large truck in a roundabout may need to:", a:["Stop in the roundabout","Use the full width, including the mountable apron","Reverse","Drive on the sidewalk"], c:1,
 w:"It may occupy both lanes on the approach. Give it room and stay back."},
{t:"intersections", q:"A cyclist in a roundabout should:", a:["Ride on the shoulder","Keep to the centre of the lane, or dismount and cross as a pedestrian","Ride against traffic","Use the centre island"], c:1,
 w:"So do not try to squeeze past one inside the circle."},
{t:"intersections", q:"You are approaching a railway crossing that has a stop sign. You must:", a:["Slow and proceed","Stop, unless directed otherwise by a flagman","Stop only if a train is coming","Sound your horn"], c:1,
 w:"A stop sign at a crossing is a stop sign."},
{t:"stopping", q:"A school bus stop arm has swung out. You may go when:", a:["The arm folds away and all lights stop flashing","The children are off the road","The amber lights come on","Ten seconds have passed"], c:0,
 w:"Arm in, lights off, then go."},
{t:"share", q:"Most buses and public vehicles must stop at railway crossings that:", a:["Have gates","Are not protected by gates, signal lights or a stop sign","Are in cities","Have a stop sign"], c:1,
 w:"School buses stop at ALL crossings, protected or not."},
{t:"night", q:"On a freeway in a snowstorm, several plows are staggered across the lanes. You should:", a:["Pass between them","Pass on the shoulder","Stay well back — never pass between plows","Sound your horn"], c:2,
 w:"The gap between staggered plows is full of snow and equipment."},
{t:"ready", q:"A rear-facing child seat may need padding underneath to sit at:", a:["A flat angle","About a 45-degree angle","A 90-degree angle","Any angle"], c:1,
 w:"Check the manufacturer instructions — the angle keeps the airway open."},
{t:"licence", q:"The G1 knowledge test covers:", a:["Only traffic signs","Only rules of the road","Traffic signs AND rules of the road, in two separate sections","Vehicle mechanics"], c:2,
 w:"20 questions each. You must pass BOTH sections."}
);
