BANK.push(
/* ══ INTERSECTIONS ══════════════════════════════════════════════════════ */
{t:"intersections", q:"An uncontrolled intersection is one with:", a:["A yield sign","No signs or traffic lights","A four-way stop","Traffic lights only"], c:1,
 w:"No signs, no lights. Common on quiet residential streets."},
{t:"intersections", q:"Two vehicles reach an uncontrolled intersection at the same time. Who goes first?", a:["The vehicle on the left","The vehicle on the right","The faster vehicle","The larger vehicle"], c:1,
 w:"Right goes first. The driver on the LEFT yields."},
{t:"intersections", q:"At an all-way stop, who has the right-of-way?", a:["The first vehicle to come to a complete stop","The vehicle on the left","The vehicle going straight","The largest vehicle"], c:0,
 w:"First to stop, first to go."},
{t:"intersections", q:"Two vehicles stop at an all-way stop at exactly the same time. Then:", a:["The vehicle on the left goes first","The vehicle on the right goes first","Both go together","The one turning goes first"], c:1,
 w:"Tie goes to the right — same as an uncontrolled intersection."},
{t:"intersections", q:"You are turning left at a green light. You must:", a:["Go immediately","Wait for oncoming traffic and pedestrians to clear","Honk first","Turn from the right lane"], c:1,
 w:"A green light is permission to enter, not a right-of-way over oncoming traffic."},
{t:"intersections", q:"Pulling out of a private driveway you must yield to:", a:["Only vehicles","Only pedestrians","Vehicles on the road AND pedestrians on the sidewalk","Nobody"], c:2,
 w:"Both. The sidewalk crosses your path first."},
{t:"intersections", q:"Which way does traffic travel inside a roundabout?", a:["Clockwise","Counter-clockwise","Either way","Depends on the roundabout"], c:1,
 w:"Counter-clockwise, always keeping right of the central island."},
{t:"intersections", q:"When entering a roundabout you should look:", a:["Right","Left","Straight ahead","Behind"], c:1,
 w:"Look LEFT. Traffic already circulating has the right-of-way."},
{t:"intersections", q:"You want to turn left at a two-lane roundabout. Which lane do you use?", a:["The right lane","The left lane","Either lane","The shoulder"], c:1,
 w:"Left lane for left turns and straight. Right lane for right turns and straight."},
{t:"intersections", q:"Once you are inside a roundabout you should:", a:["Stop to let others in","Keep moving unless you must avoid a collision","Change lanes freely","Reverse if you miss your exit"], c:1,
 w:"You have the right-of-way over entering traffic. Do not stop and do not change lanes."},
{t:"intersections", q:"You missed your exit in the inside lane of a roundabout. You should:", a:["Stop and reverse","Cut across to the exit","Continue around until you reach it again","Drive over the centre island"], c:2,
 w:"Go around again. Cutting across is how roundabout crashes happen."},
{t:"intersections", q:"When should you signal in a roundabout?", a:["On entry only","Never","Right-turn signal once you pass the exit before yours","Left signal the whole way"], c:2,
 w:"Signal right after passing the exit before the one you want."},
{t:"intersections", q:"An emergency vehicle approaches while you are already in a roundabout. You should:", a:["Stop immediately","Exit at your intended exit, then pull over past the island","Reverse out","Drive onto the centre island"], c:1,
 w:"Never stop inside a roundabout. Clear it first, then pull over."},
{t:"intersections", q:"At a pedestrian crossover you must:", a:["Slow down","Yield and wait until pedestrians have completely crossed","Stop only if they are in your lane","Sound your horn"], c:1,
 w:"Completely across the whole road — not just past your car."},
{t:"intersections", q:"Failing to stop at a pedestrian crossover costs:", a:["2 demerit points","3 demerit points","4 demerit points","6 demerit points"], c:2,
 w:"4 points plus a fine, and higher in a community safety zone."},
{t:"intersections", q:"You may not pass another vehicle within what distance of a pedestrian crossover?", a:["10 metres","15 metres","30 metres","50 metres"], c:2,
 w:"30 metres. The car you would pass may be stopped for someone you cannot see."},
{t:"intersections", q:"Blocking an intersection when traffic is backed up is:", a:["Fine if the light is green","Illegal and dangerous","Only a problem downtown","Allowed during rush hour"], c:1,
 w:"Do not enter unless you can clear the far side."},
{t:"intersections", q:"Approaching a railway crossing with a train coming, you must stop at least:", a:["3 metres from the nearest rail","5 metres from the nearest rail","10 metres from the nearest rail","15 metres from the nearest rail"], c:1,
 w:"5 metres from the nearest rail or gate."},
{t:"intersections", q:"How long can it take a train to stop under full emergency braking?", a:["100 metres","500 metres","Up to 2 kilometres","Up to 10 kilometres"], c:2,
 w:"Two kilometres. You cannot win that race, ever."},
{t:"intersections", q:"A railway gate is rising as you approach. You should:", a:["Drive through quickly","Wait until it is fully raised","Drive around it","Reverse"], c:1,
 w:"Never drive around, under or through a gate that is down, lowering or rising."},
{t:"intersections", q:"Which vehicles must stop at every railway crossing?", a:["Trucks","School buses","Taxis","Motorcycles"], c:1,
 w:"School buses stop at all crossings, gates or not — and they do NOT use their red lights for it."},
{t:"intersections", q:"You are trapped on railway tracks. You should:", a:["Stay in the vehicle","Get everyone out and away, then call authorities","Try to push the car","Wait for the train to pass"], c:1,
 w:"Get out, get well away from the tracks, then call."},
{t:"intersections", q:"When crossing railway or streetcar tracks you should cross:", a:["At a shallow angle","At about 90 degrees","While braking","While shifting gears"], c:1,
 w:"Square to the rails, so your tires do not get caught. And do not shift while crossing."},
{t:"intersections", q:"A traffic light is completely dark (no power). You should treat it as:", a:["A green light","An all-way stop","A yield","Ignore it"], c:1,
 w:"Treat a blank signal exactly like an all-way stop."},

/* ══ STOPPING ═══════════════════════════════════════════════════════════ */
{t:"stopping", q:"Where must you stop at an intersection with a marked stop line?", a:["At the stop line","At the crosswalk","At the edge of the sidewalk","Wherever you can see"], c:0,
 w:"The order is: stop line, then crosswalk, then sidewalk edge, then intersection edge."},
{t:"stopping", q:"There is no stop line and no crosswalk, but there is a sidewalk. Stop at:", a:["The intersection edge","The edge of the sidewalk","The middle of the sidewalk","Anywhere"], c:1,
 w:"Sidewalk edge — people walking there come before you."},
{t:"stopping", q:"A complete stop means:", a:["Slowing to walking pace","Rolling slowly through","Your wheels stop turning","Any speed under 10 km/h"], c:2,
 w:"Wheels stop. A rolling stop is a ticket."},
{t:"stopping", q:"A school crossing guard is holding up a stop sign. You must:", a:["Slow down","Stop until every person AND the guard are off the road","Stop only if children are crossing","Pass carefully"], c:1,
 w:"The guard is the last one off the road. Wait for them."},
{t:"stopping", q:"Ignoring a school crossing guard costs:", a:["1 demerit point","2 demerit points","3 demerit points","6 demerit points"], c:2,
 w:"3 points plus a substantial fine."},
{t:"stopping", q:"Which foot should you use for the brake and the gas?", a:["Left for brake, right for gas","Right foot for both","Either","Whichever is comfortable"], c:1,
 w:"One foot, so you can never press both at once."},
{t:"stopping", q:"Going down a long steep hill with a manual transmission you should:", a:["Shift into neutral","Ride the brakes","Downshift to a lower gear before the descent","Shift into a higher gear"], c:2,
 w:"Gear down BEFORE you start down. Use the same gear you would use going up."},
{t:"stopping", q:"With anti-lock brakes (ABS) in an emergency stop you should:", a:["Pump the brake","Press hard and hold, and keep steering","Press lightly","Use the parking brake"], c:1,
 w:"Expect the pedal to pulse. That is the system working, not failing."},
{t:"stopping", q:"ABS is designed to:", a:["Shorten your stopping distance","Let you steer while braking hard","Replace winter tires","Stop the car automatically"], c:1,
 w:"Do NOT count on ABS for a shorter stop. It buys you steering, not distance."},
{t:"stopping", q:"Threshold braking in a vehicle without ABS means:", a:["Pumping the pedal rapidly","Braking hard, then easing slightly when a wheel locks","Using the parking brake","Braking gently"], c:1,
 w:"Brake to the edge of lockup, ease off just enough to unlock, reapply. Do not pump."},
{t:"stopping", q:"A safe and responsible driver stops by:", a:["Braking late and hard","Seeing the stop early, checking mirrors, braking early and smoothly","Coasting in neutral","Using the parking brake"], c:1,
 w:"Early and smooth also warns the driver behind you."},

/* ══ TURNING ════════════════════════════════════════════════════════════ */
{t:"turns", q:"A right turn should begin and end:", a:["In the centre lane","Close to the right side of the road","In the left lane","Wherever there is room"], c:1,
 w:"Right side in, right side out — unless signs or markings say otherwise."},
{t:"turns", q:"A left turn should begin and end:", a:["In the far left lane in your direction","In the right lane","In the centre of the road","In any lane"], c:0,
 w:"Far left lane in, far left lane out."},
{t:"turns", q:"Turning right on a red light is:", a:["Never allowed in Ontario","Allowed after a complete stop unless a sign prohibits it","Allowed without stopping","Only allowed outside cities"], c:1,
 w:"Full stop first, then yield to everyone, then go — unless a NO RIGHT TURN ON RED sign is posted."},
{t:"turns", q:"You may turn LEFT on a red light when:", a:["Never","Turning from a one-way road onto a one-way road, after a full stop","Traffic is clear","Turning onto a two-way road"], c:1,
 w:"One-way to one-way only, and only after a complete stop."},
{t:"turns", q:"While waiting to turn left, your front wheels should be:", a:["Turned left, ready to go","Pointed straight ahead","Turned right","It does not matter"], c:1,
 w:"If you are rear-ended with wheels turned left, you get pushed into oncoming traffic."},
{t:"turns", q:"A two-way left-turn lane (centre lane, arrows both ways) may be used for:", a:["Passing slower traffic","Left turns only, from either direction","Driving along","Parking"], c:1,
 w:"Turns only. Never use it to pass or to travel in."},
{t:"turns", q:"Before making a U-turn you must be able to see at least:", a:["50 metres in both directions","100 metres in both directions","150 metres in both directions","200 metres in both directions"], c:2,
 w:"150 m each way, and never on a curve, hilltop, or near a bridge, tunnel or railway crossing."},
{t:"turns", q:"Deciding whether to make a U-turn, your FIRST consideration is:", a:["Your car's turning radius","Traffic regulations","The height of the curb","Nearby fire hydrants"], c:1,
 w:"Is it even legal here? Straight from the handbook sample test."},
{t:"turns", q:"A three-point turn begins:", a:["From the centre of the road","From the far right side of the road","From the left lane","From a driveway"], c:1,
 w:"Start far right so you have the whole road width to work with."},
{t:"turns", q:"When reversing you should:", a:["Rely on the backup camera","Turn and look over your shoulder in the direction you are moving","Use mirrors only","Reverse quickly"], c:1,
 w:"Look over your shoulder, check the other side too, and watch for children and cyclists."},
{t:"turns", q:"Reversing is illegal on a divided road with a speed limit over:", a:["50 km/h","60 km/h","80 km/h","100 km/h"], c:2,
 w:"Over 80 km/h on a divided road: no reversing, except to help in an emergency."},
{t:"turns", q:"When should you finish braking for a turn?", a:["While turning the wheel","Before you turn the wheel","After the turn","Halfway through"], c:1,
 w:"Brake in a straight line, then steer. Braking and steering together costs you grip."},
{t:"turns", q:"Turning right, you should check your right blind spot for:", a:["Oncoming cars","Cyclists and pedestrians","Traffic lights","Parked cars"], c:1,
 w:"A cyclist coming up on your right is the classic right-hook collision."},
{t:"turns", q:"Turning left onto a one-way street, you should end up in:", a:["Any lane","The far left lane of that street","The right lane","The centre lane"], c:1,
 w:"Left turn, left lane. Same principle everywhere."},

/* ══ LANES & PASSING ════════════════════════════════════════════════════ */
{t:"positions", q:"The correct order for a lane change is:", a:["Signal, steer, check","Check mirrors, shoulder check, signal, check again, steer","Signal and steer","Shoulder check then steer"], c:1,
 w:"Mirrors, blind spot, signal, re-check, then move — smoothly and at the same speed."},
{t:"positions", q:"While changing lanes you should:", a:["Slow down","Maintain your speed or gently increase it","Brake gently","Accelerate hard"], c:1,
 w:"Slowing mid-change is how you get rear-ended."},
{t:"positions", q:"You should not change lanes:", a:["On a highway","In or near an intersection","In the rain","When passing"], c:1,
 w:"Also avoid weaving in heavy traffic or bad weather."},
{t:"positions", q:"You may return to your lane after passing when:", a:["You clear their front bumper","You can see the entire front of the vehicle in your inside mirror","You have counted 3 seconds","They flash their lights"], c:1,
 w:"Whole front of their car in your rear-view mirror. Then signal and move over."},
{t:"positions", q:"Passing to the left of the centre line is prohibited within what distance of a bridge, viaduct or tunnel?", a:["10 metres","15 metres","30 metres","50 metres"], c:2,
 w:"30 metres — the same figure as a pedestrian crossover."},
{t:"positions", q:"You may pass on the right:", a:["Never","On multi-lane or one-way roads, or when overtaking a streetcar or left-turning vehicle","Any time","Only on highways"], c:1,
 w:"Legal in those cases, but always more dangerous than passing on the left."},
{t:"positions", q:"You may drive on the shoulder to pass:", a:["Never","Only on the right, only if paved, and only to pass a left-turning vehicle","Any time the shoulder is clear","On the left shoulder only"], c:1,
 w:"Right shoulder, paved, left-turning vehicle. Nothing else."},
{t:"positions", q:"You must never pass:", a:["A city bus","A moving snow plow","A taxi","A motorcycle"], c:1,
 w:"Never pass a working snow plow. On freeways they run staggered — never squeeze between them."},
{t:"positions", q:"Another driver is passing you. You should:", a:["Speed up","Move closer to the right and be ready to slow down","Move left","Brake hard"], c:1,
 w:"Never race someone who is passing you. Let them finish."},
{t:"positions", q:"Passing at night, you should:", a:["Keep high beams on the whole time","Use low beams approaching, high beams as you pull alongside","Use only parking lights","Flash your lights"], c:1,
 w:"Low on approach so you do not blind them, high once alongside so you can see."},
{t:"positions", q:"Passing on a hill crest or blind curve is:", a:["Allowed if you are quick","Allowed with a signal","Prohibited","Allowed at night"], c:2,
 w:"If you cannot see the road ahead, you cannot know it is clear."},
{t:"positions", q:"It is illegal and dangerous for a slower vehicle to:", a:["Use the right lane","Cut in front of a faster moving vehicle","Signal early","Drive at the limit"], c:1,
 w:"Straight from the freeway section of the handbook."},

/* ══ PARKING ════════════════════════════════════════════════════════════ */
{t:"parking", q:"You may not park within what distance of a fire hydrant?", a:["1 metre","3 metres","6 metres","9 metres"], c:1,
 w:"3 metres. Firefighters need the hose run clear."},
{t:"parking", q:"You may not park within what distance of an intersection controlled by traffic lights?", a:["3 metres","9 metres","15 metres","30 metres"], c:2,
 w:"15 m at a signalised intersection, 9 m at an uncontrolled one."},
{t:"parking", q:"You may not park within what distance of an uncontrolled intersection?", a:["3 metres","6 metres","9 metres","15 metres"], c:2,
 w:"9 metres — sight lines matter more than convenience."},
{t:"parking", q:"You may not park within what distance of the nearest rail of a railway crossing?", a:["5 metres","9 metres","15 metres","30 metres"], c:2,
 w:"15 metres from the nearest rail."},
{t:"parking", q:"You may not park within what distance of a bridge?", a:["15 metres","30 metres","60 metres","100 metres"], c:3,
 w:"100 metres on or near a bridge."},
{t:"parking", q:"You may not park within what distance of the entrance to a hotel, theatre or public hall?", a:["3 metres","6 metres","9 metres","15 metres"], c:1,
 w:"6 metres from a public building entrance."},
{t:"parking", q:"When parking on a road you must have a clear view for at least:", a:["50 metres in both directions","75 metres in both directions","125 metres in both directions","200 metres in both directions"], c:2,
 w:"125 metres each way. Never park on a curve or hill crest."},
{t:"parking", q:"Parked facing DOWNHILL with a curb, your front wheels should point:", a:["Toward the curb","Away from the curb","Straight ahead","It does not matter"], c:0,
 w:"Downhill: wheels INTO the curb, so gravity wedges you against it."},
{t:"parking", q:"Parked facing UPHILL with a curb, your front wheels should point:", a:["Toward the curb","Left, toward the road","Straight ahead","Either way"], c:1,
 w:"Uphill with a curb: turn left so rolling back catches the curb."},
{t:"parking", q:"Parked facing UPHILL with NO curb, your wheels should point:", a:["Left","Sharply right","Straight","Toward the centre line"], c:1,
 w:"No curb means turn sharply right so a rollback takes you off the road, not into traffic."},
{t:"parking", q:"How far from the curb should you finish parallel parking?", a:["About 10 cm","About 30 cm","About 60 cm","About 1 metre"], c:1,
 w:"About 30 centimetres — a hand span."},
{t:"parking", q:"A parallel parking space should be at least:", a:["The same length as your vehicle","1.5 times your vehicle length","Twice your vehicle length","3 metres longer"], c:1,
 w:"One and a half car lengths gives you room to swing in."},
{t:"parking", q:"You may park in an accessible parking space:", a:["For a few minutes","If no one else needs it","Only if you display a valid Accessible Parking Permit","If you are picking someone up"], c:2,
 w:"Permit or nothing. The fines are steep."},
{t:"parking", q:"If you must stop on a highway you should:", a:["Stop in the right lane","Pull completely onto the shoulder and use hazard lights","Stop on the median","Stop in the left lane"], c:1,
 w:"Never leave any part of your vehicle in a travelled lane."}
);
