/* ── Topics ──────────────────────────────────────────────────────────────
   ch1 / ch2 map to the two handbook chapters; "extra" marks material the
   G1 test asks about that sits outside those two chapters.               */
const TOPICS = [
  {id:"licence",  name:"Getting Your Licence", chap:"Chapter 1", blurb:"G1, G2, G — the rules of the ladder"},
  {id:"ready",    name:"Before You Move",      chap:"Chapter 2", blurb:"Seat, belts, mirrors, lights"},
  {id:"along",    name:"Driving Along",        chap:"Chapter 2", blurb:"Speed, space, signals"},
  {id:"share",    name:"Sharing the Road",     chap:"Chapter 2", blurb:"Bikes, trucks, buses, walkers"},
  {id:"intersections", name:"Intersections",   chap:"Chapter 2", blurb:"Who goes first, roundabouts"},
  {id:"stopping", name:"Stopping",             chap:"Chapter 2", blurb:"Stop lines, school buses, trains"},
  {id:"turns",    name:"Turning Around",       chap:"Chapter 2", blurb:"Left, right, U-turns, reversing"},
  {id:"positions",name:"Lanes & Passing",      chap:"Chapter 2", blurb:"Changing lanes, overtaking"},
  {id:"parking",  name:"Parking",              chap:"Chapter 2", blurb:"Where you can and cannot"},
  {id:"freeway",  name:"Freeway Driving",      chap:"Chapter 2", blurb:"Merging, HOV, exits"},
  {id:"night",    name:"Night & Bad Weather",  chap:"Chapter 2", blurb:"Fog, ice, skids, glare"},
  {id:"emergencies", name:"Emergencies",       chap:"Chapter 2", blurb:"Collisions, failures, blowouts"},
  {id:"lights",   name:"Lights & Lines",       chap:"Signs",     blurb:"Signals and pavement markings"},
  {id:"penalties",name:"Points & Penalties",   chap:"Extra",     blurb:"Demerits, suspensions, impairment"}
];

/* q = question · a = options · c = index of the correct one · w = why */
const BANK = [

/* ══ CHAPTER 1 — GETTING YOUR LICENCE ═══════════════════════════════════ */
{t:"licence", q:"How old must you be to apply for a G1 licence in Ontario?", a:["14","15","16","18"], c:2,
 w:"16 is the floor. You also need a vision test and the knowledge test."},
{t:"licence", q:"What two tests must you pass to get your G1?", a:["Vision test and knowledge test","Road test and vision test","Knowledge test and road test","Vision test only"], c:0,
 w:"The knowledge test is the one you are studying for: 20 signs + 20 rules."},
{t:"licence", q:"How long must you normally hold a G1 before the first road test?", a:["4 months","8 months","12 months","24 months"], c:2,
 w:"12 months — or 8 months if you finish an approved Beginner Driver Education course."},
{t:"licence", q:"An approved driver education course shortens your G1 stage to:", a:["6 months","8 months","10 months","It does not shorten it"], c:1,
 w:"Course credit cuts 4 months off, 12 down to 8. It may also cut your insurance."},
{t:"licence", q:"How long do you have to complete the whole graduated licensing system?", a:["2 years","3 years","5 years","No limit"], c:2,
 w:"5 years. Run out of time and you start over from the beginning."},
{t:"licence", q:"What is the minimum time to go from G1 all the way to a full G licence?", a:["12 months","20 months","24 months","36 months"], c:1,
 w:"8 months at G1 with driver ed, plus 12 months at G2 = 20 months minimum."},
{t:"licence", q:"As a G1 driver, what is your legal blood alcohol limit?", a:["Zero","0.05","0.08","0.05 if over 21"], c:0,
 w:"Zero. Nothing. Not one drink."},
{t:"licence", q:"Where must your accompanying driver sit when you drive as a G1?", a:["Anywhere in the vehicle","Front passenger seat","Directly behind you","Either front seat"], c:1,
 w:"Front passenger seat, every time — they need to see what you see."},
{t:"licence", q:"How much driving experience must your G1 accompanying driver have?", a:["At least 1 year","At least 2 years","At least 4 years","At least 10 years"], c:2,
 w:"4 years minimum, with a valid Class G or higher licence."},
{t:"licence", q:"Your G1 accompanying driver must have a blood alcohol level below:", a:["Zero","0.02","0.05","0.08"], c:2,
 w:"Under 0.05. They are effectively the driver in charge, so they must be sober enough to take over."},
{t:"licence", q:"When may a G1 driver NOT drive?", a:["Between midnight and 5 a.m.","Between 11 p.m. and 6 a.m.","On weekends","During rush hour"], c:0,
 w:"Midnight to 5 a.m. is off limits for G1 drivers — no exceptions."},
{t:"licence", q:"A G1 driver may drive on a 400-series highway only if:", a:["It is daytime","Traffic is light","The accompanying driver is a licensed driving instructor","They have held the G1 for 6 months"], c:2,
 w:"Only with a licensed driving instructor beside you. Otherwise, stay off."},
{t:"licence", q:"Which of these is a G1 driver banned from driving on?", a:["Any road with a painted centre line","The Don Valley Parkway","Any road inside a city","Gravel roads"], c:1,
 w:"DVP, Gardiner, QEW, E.C. Row and Conestoga Parkway are all off limits to G1 drivers."},
{t:"licence", q:"How many passengers may a G1 driver carry?", a:["Only the accompanying driver","One besides the accompanying driver","As many as there are working seatbelts","None"], c:2,
 w:"There is no passenger count limit — but every single person needs a working seatbelt."},
{t:"licence", q:"A G2 driver aged 19 or under, in their FIRST 6 months, driving between midnight and 5 a.m., may carry:", a:["No passengers","1 passenger aged 19 or under","3 passengers aged 19 or under","Any number"], c:1,
 w:"One young passenger for the first 6 months. This rule kills a lot of new licences."},
{t:"licence", q:"After 6 months as a G2, a driver aged 19 or under may carry how many passengers aged 19 or under between midnight and 5 a.m.?", a:["1","2","3","Unlimited"], c:2,
 w:"Up to 3 — until they turn 20 or get a full G."},
{t:"licence", q:"The G2 late-night passenger limits do NOT apply when:", a:["You are driving to work","The passengers are immediate family","It is a weekend","You are on a highway"], c:1,
 w:"Immediate family are exempt, and so is having a fully licensed driver in the front passenger seat."},
{t:"licence", q:"Which drivers must keep a ZERO blood alcohol level?", a:["G1 and G2 only","All drivers 21 and under, plus all novice drivers","Drivers under 18","Only G1 drivers"], c:1,
 w:"Novice (G1/G2/M1/M2) drivers AND every driver aged 21 or under."},
{t:"licence", q:"Before taking the G2 exit road test you must declare that you have:", a:["Driven at least 100 hours","Highway driving experience at 80 km/h or more","Owned a car for 6 months","Passed a first aid course"], c:1,
 w:"You sign a Declaration of Highway Driving Experience. Freeway skill is the point of the G test."},
{t:"licence", q:"How early should you arrive for a road test?", a:["Right on time","10 minutes early","At least 30 minutes early","1 hour early"], c:2,
 w:"30 minutes. Late means a forfeited fee and a new booking."},
{t:"licence", q:"What is the minimum wait between road test attempts?", a:["24 hours","10 days","30 days","3 months"], c:1,
 w:"10 days — use them to fix what the examiner listed on your report."},
{t:"licence", q:"You cancel a road test with less than 48 hours notice. What happens?", a:["Nothing","You lose the prepaid fee","You wait 30 days","You get a warning"], c:1,
 w:"Under 48 hours or a no-show and the prepaid fee is gone."},
{t:"licence", q:"Which is NOT allowed during your road test?", a:["Wearing your glasses","Using the backup camera and lane monitoring","Adjusting your mirrors first","Driving your own car"], c:1,
 w:"Electronic driving aids are off. The examiner needs to see YOUR shoulder checks and mirror checks."},
{t:"licence", q:"Who may ride along during your road test?", a:["A parent","Your driving instructor","A translator","Only the examiner"], c:3,
 w:"Examiner only. No friends, relatives, instructors, translators or pets."},
{t:"licence", q:"A minimum Beginner Driver Education course is how many hours?", a:["20","30","40","60"], c:2,
 w:"40 hours total: 20 classroom, 10 in-vehicle, 10 flexible."},
{t:"licence", q:"New to Ontario from another province? You must get an Ontario licence within:", a:["30 days","60 days","6 months","1 year"], c:1,
 w:"60 days to switch over."},
{t:"licence", q:"When may you lend someone your driver's licence?", a:["In an emergency","To a person learning to drive","For identification","It is never permitted"], c:3,
 w:"Never. Straight from the handbook sample test."},
{t:"licence", q:"A Class G licence lets you drive:", a:["Any vehicle including buses","Cars, vans and small trucks","Motorcycles only","Tractor-trailers"], c:1,
 w:"Cars, vans, small trucks, and towed vehicles up to the posted weight limits."},
{t:"licence", q:"Which licence class covers motorcycles?", a:["Class A","Class D","Class M","Class F"], c:2,
 w:"M is for motorcycles, with M1 and M2 as the graduated steps."},
{t:"licence", q:"After you get your licence, a new medical condition that affects your driving must be:", a:["Kept private","Reported to the ministry","Reported only at renewal","Reported to your insurer only"], c:1,
 w:"Report it. Doctors and optometrists are also required to report unsafe drivers over 16."},
{t:"licence", q:"How long does a novice driver stay at Level Two (G2) minimum?", a:["6 months","8 months","12 months","18 months"], c:2,
 w:"12 months at G2 before the final road test."},
{t:"licence", q:"Someone offers to sell you a licence with no test. This is:", a:["A legitimate fast-track service","A scam — report it","Allowed for new residents","Only legal outside Ontario"], c:1,
 w:"MTO and DriveTest never charge booking fees or guarantee passes. Only ontario.ca and drivetest.ca are real."},

/* ══ BEFORE YOU MOVE ════════════════════════════════════════════════════ */
{t:"ready", q:"You must wear a seatbelt:", a:["Only on highways","Only in the front seat","Every time you travel in a vehicle with seatbelts","Only above 60 km/h"], c:2,
 w:"Every trip, every seat, no exceptions."},
{t:"ready", q:"Not wearing your seatbelt as the driver costs you a fine plus:", a:["0 demerit points","2 demerit points","4 demerit points","6 demerit points"], c:1,
 w:"2 points, plus the fine."},
{t:"ready", q:"A driver who does not provide a working seatbelt for every passenger can lose their licence for:", a:["7 days","At least 30 days","90 days","1 year"], c:1,
 w:"Minimum 30-day suspension. This is exactly why G1 passenger counts are capped by belts."},
{t:"ready", q:"Where must the shoulder strap sit?", a:["Under your arm","Behind your back","Over your shoulder and across the centre of your chest","Across your stomach"], c:2,
 w:"Under the arm or behind the back turns a seatbelt into a decoration."},
{t:"ready", q:"An infant weighing under 9 kg must ride in:", a:["A forward-facing seat","A rear-facing child car seat in the back","A booster seat","A regular seatbelt"], c:1,
 w:"Rear-facing, in the back, never in front of an active airbag."},
{t:"ready", q:"A booster seat is required for a child who:", a:["Is over 8 years old","Weighs 18-36 kg and is under 145 cm and under 8","Weighs over 36 kg","Is taller than 145 cm"], c:1,
 w:"Boosters cover roughly 18-36 kg, under 145 cm, under age 8."},
{t:"ready", q:"A child can move to a seatbelt alone once they:", a:["Turn 8, OR reach 36 kg, OR reach 145 cm","Turn 8 AND reach 36 kg AND reach 145 cm","Turn 10","Ask to"], c:0,
 w:"Any ONE of the three is enough."},
{t:"ready", q:"A correctly installed child seat should move no more than:", a:["2.5 cm","5 cm","10 cm","It should not move at all"], c:0,
 w:"2.5 cm (1 inch) at the belt path. Push down with your body weight while tightening."},
{t:"ready", q:"Children under what age are safest in the back seat?", a:["8","10","13","16"], c:2,
 w:"Under 13, back seat. Airbags are built for adult bodies."},
{t:"ready", q:"Your blind spots are:", a:["Areas your mirrors cannot show you","The area right in front of your hood","Behind the sun visor","Only a problem at night"], c:0,
 w:"The only cure is a shoulder check. Mirrors alone will not do it."},
{t:"ready", q:"You should be able to see the road how far in front of your vehicle?", a:["1 metre","4 metres","10 metres","20 metres"], c:1,
 w:"Sit high enough to see 4 m ahead over the hood."},
{t:"ready", q:"Where should your head restraint sit?", a:["Level with your neck","Level with the back of your head","As low as possible","It does not matter"], c:1,
 w:"Level with the back of your head — that is what stops whiplash."},
{t:"ready", q:"Headlights must be turned on:", a:["Only after full dark","From half an hour before sunset to half an hour after sunrise","Only in rain","Only on highways"], c:1,
 w:"Half hour before sunset to half hour after sunrise, and whenever visibility drops under 150 m."},
{t:"ready", q:"You must switch from high beams to low beams within what distance of an oncoming vehicle?", a:["30 metres","60 metres","150 metres","300 metres"], c:2,
 w:"150 m for oncoming. 60 m when following someone."},
{t:"ready", q:"When following another vehicle, use low beams when you are within:", a:["30 metres","60 metres","150 metres","200 metres"], c:1,
 w:"60 m — your high beams bounce straight out of their mirrors."},
{t:"ready", q:"Daytime running lights are a problem at dusk because:", a:["They are too bright","They do not turn on your tail lights","They drain the battery","They are illegal"], c:1,
 w:"No tail lights means nobody behind you can see you. Use full headlights."},
{t:"ready", q:"Your headlights must make objects visible at least:", a:["50 metres away","110 metres away","150 metres away","200 metres away"], c:1,
 w:"They must shine white light 150 m ahead and reveal objects 110 m away."},
{t:"ready", q:"Where should your hands sit on the steering wheel?", a:["12 o'clock","10 and 2","9 and 3","Wherever is comfortable"], c:2,
 w:"9 and 3. It is the safest position if the airbag fires."},
{t:"ready", q:"Before driving you should NOT:", a:["Adjust your mirrors","Check your warning lights","Drive if you are upset or angry","Fasten your seatbelt"], c:2,
 w:"Strong emotions wreck your reaction time as surely as alcohol does."},
{t:"ready", q:"Loose objects in the passenger compartment should be:", a:["Left on the seat","Put on the floor","Secured with a net or moved to the trunk","Held by a passenger"], c:2,
 w:"In a crash, a loose water bottle becomes a projectile."},

/* ══ DRIVING ALONG ══════════════════════════════════════════════════════ */
{t:"along", q:"With no posted sign, the speed limit in a city, town or village is:", a:["40 km/h","50 km/h","60 km/h","80 km/h"], c:1,
 w:"50 in built-up areas. This is a favourite exam question."},
{t:"along", q:"With no posted sign, the speed limit outside a built-up area is:", a:["50 km/h","60 km/h","80 km/h","100 km/h"], c:2,
 w:"80 km/h is the default outside cities and towns."},
{t:"along", q:"A posted speed limit is:", a:["A target speed","A minimum","The maximum in ideal conditions","A suggestion"], c:2,
 w:"It is the top speed when conditions are perfect. Rain, snow or traffic means slower."},
{t:"along", q:"You should always drive at a speed that lets you:", a:["Stop within 150 metres","Stop within 90 metres","Stop within 60 metres","Stop within a safe distance"], c:3,
 w:"Straight from the handbook: within a safe distance for the conditions."},
{t:"along", q:"The minimum following distance behind the vehicle ahead is:", a:["1 second","2 seconds","4 seconds","1 car length"], c:1,
 w:"2 seconds in good conditions. More in bad weather, or behind bikes and trucks."},
{t:"along", q:"How do you measure a two-second following distance?", a:["Count car lengths","Pick a marker and count after the vehicle ahead passes it","Watch your speedometer","Estimate in metres"], c:1,
 w:"Pick a pole. When their back bumper passes it, count 'one thousand and one, one thousand and two'. Reach it early? Too close."},
{t:"along", q:"You should increase your following distance when:", a:["Following a motorcycle or a large truck","Driving downhill","Driving on a one-way road","Driving during the day"], c:0,
 w:"Also in bad weather and when carrying a heavy load."},
{t:"along", q:"How often should you check your mirrors?", a:["Every 5 seconds","Every 30 seconds","Every minute","Only before turning"], c:0,
 w:"Roughly every 5 seconds, so you always know what is behind you."},
{t:"along", q:"On a multi-lane road you should normally drive:", a:["In the left lane","In the right lane","In the centre lane","Wherever there is space"], c:1,
 w:"Keep right. Left lanes are for passing."},
{t:"along", q:"Signalling a lane change means:", a:["You now have the right-of-way","Other drivers must let you in","You are telling others what you intend to do","You do not need to shoulder check"], c:2,
 w:"Signalling never gives you the right-of-way. It only announces the plan."},
{t:"along", q:"When must you use your signals?", a:["Only when turning","When turning, changing lanes, slowing, stopping or pulling out","Only in traffic","Only on highways"], c:1,
 w:"Any change of direction or speed that affects others."},
{t:"along", q:"Your mechanical signals fail. You may:", a:["Drive without signalling","Use hand signals","Use your hazard lights instead","Only turn right"], c:1,
 w:"Hand signals are legal and every driver should know them."},
{t:"along", q:"A police officer directs you to do something that contradicts a traffic light. You should:", a:["Obey the light","Obey the officer","Stop and wait","Take another route"], c:1,
 w:"Police directions beat signs and signals, always."},
{t:"along", q:"When a police officer signals you to pull over you must:", a:["Slow down and keep going","Pull over as far right as safe, stop, and stay in the vehicle","Get out and walk back","Pull over on the left"], c:1,
 w:"Stay in your vehicle. Have your licence, permit and insurance ready."},
{t:"along", q:"Failing to stop for police carries how many demerit points?", a:["3","4","6","7"], c:3,
 w:"7 points — tied with failing to remain at a collision for the worst on the chart."},
{t:"along", q:"Driving in another vehicle's blind spot is:", a:["Fine if you signal","Dangerous — they cannot see you","Only a problem for trucks","Required when passing"], c:1,
 w:"Speed up or drop back. Do not live there."},
{t:"along", q:"You are being tailgated. You should:", a:["Speed up","Brake to warn them","Move right and let them pass","Ignore it"], c:2,
 w:"Let them go. Brake-checking a tailgater invites a rear-end collision."},

/* ══ SHARING THE ROAD ═══════════════════════════════════════════════════ */
{t:"share", q:"When passing a cyclist you must leave at least:", a:["0.5 metres","1 metre","2 metres","3 metres"], c:1,
 w:"1 metre where practical. Less is a fine plus 2 demerit points."},
{t:"share", q:"Before opening your car door you must:", a:["Signal","Check mirrors and blind spot for cyclists","Turn off the engine","Nothing"], c:1,
 w:"Dooring a cyclist is a serious offence — 3 demerit points."},
{t:"share", q:"A bike lane is marked by:", a:["A broken white line","A solid white line and a bike symbol","A yellow line","A dashed yellow line"], c:1,
 w:"You may only enter it briefly, and only to turn right."},
{t:"share", q:"Two chevrons and a bicycle painted on the lane (a sharrow) means:", a:["Bikes only","Cars only","Cyclists share this lane with cars","No cycling"], c:2,
 w:"Sharrows mark a shared lane. Expect riders in the middle of it."},
{t:"share", q:"A bike box at an intersection is where:", a:["You stop your car","Cyclists wait ahead of stopped traffic","Bikes are parked","Cars turn right"], c:1,
 w:"Stop behind it, never inside it."},
{t:"share", q:"If you cannot see a truck driver's face in their side mirror:", a:["You are fine","They cannot see you","You should honk","Move closer"], c:1,
 w:"That is the definition of a truck's blind spot. Get out of it."},
{t:"share", q:"A large truck turning right may first swing:", a:["Right","Left","Backwards","It does not swing"], c:1,
 w:"Never dive into the gap on their right — you get squeezed between the trailer and the curb."},
{t:"share", q:"Compared to a car, a large truck needs:", a:["A shorter stopping distance","About the same stopping distance","A much longer stopping distance","No braking distance"], c:2,
 w:"Never cut in close in front of one."},
{t:"share", q:"You must stop for a school bus with upper red lights flashing when you are:", a:["Behind it only","In front of it only","Behind it or approaching it from the front","Only on a two-lane road"], c:2,
 w:"Both directions — unless a median physically separates you."},
{t:"share", q:"Approaching a stopped school bus from behind, you must stop at least:", a:["5 metres away","10 metres away","20 metres away","30 metres away"], c:2,
 w:"20 metres. Give kids room to cross."},
{t:"share", q:"On a road with a median strip, who must stop for a school bus with red lights flashing?", a:["Everyone","Only vehicles behind the bus","Only oncoming vehicles","Nobody"], c:1,
 w:"A median is a physical barrier, so oncoming traffic keeps moving."},
{t:"share", q:"Failing to stop for a school bus with red lights flashing costs (first offence):", a:["2 demerit points","3 demerit points","4 demerit points","6 demerit points"], c:3,
 w:"6 points and a heavy fine. Witnesses can report you."},
{t:"share", q:"Amber lights flashing on a school bus mean:", a:["It is about to stop — prepare to stop","It is pulling away","Pass with caution","Ignore it"], c:0,
 w:"Amber is the warning. Red is the order."},
{t:"share", q:"The school bus law applies:", a:["Only during school hours","Only on two-lane roads","On any road, at any time, at any speed limit","Only in school zones"], c:2,
 w:"Any road, any time, any number of lanes."},
{t:"share", q:"You must pass a streetcar on which side?", a:["The left","The right, unless it is a one-way road","Either side","You may never pass one"], c:1,
 w:"Right side, except on a one-way road."},
{t:"share", q:"At a streetcar stop with no safety island, you must stay how far behind the rear doors?", a:["1 metre","2 metres","5 metres","10 metres"], c:1,
 w:"At least 2 metres behind the rear doors while passengers get on and off."},
{t:"share", q:"A streetcar safety island means you may:", a:["Stop and wait","Pass at a reasonable speed, ready for pedestrians","Drive over it","Park on it"], c:1,
 w:"The island protects passengers — but slow down anyway."},
{t:"share", q:"An orange triangle with a red border on the back of a vehicle means it travels at:", a:["40 km/h or less","60 km/h or less","80 km/h or less","Any speed"], c:0,
 w:"Slow-moving vehicle: farm equipment, horse-drawn buggies, road machines."},
{t:"share", q:"Approaching a horse-drawn vehicle you should:", a:["Sound your horn","Pass as closely as possible","Pass with as much room as you can, quietly","Speed up to get by"], c:2,
 w:"Noise and a close pass can spook the horse into your lane."},
{t:"share", q:"Motorized wheelchairs and scooters on the road count as:", a:["Vehicles","Pedestrians","Bicycles","Motorcycles"], c:1,
 w:"Treat them exactly like people on foot."},
{t:"share", q:"Motorcycle turn signals are a hazard because:", a:["They are dim","They may not shut off automatically","They flash too fast","They are on the back only"], c:1,
 w:"Wait until you see the bike actually turn before you commit."},
{t:"share", q:"A city bus signals to pull out of a bus bay. You must:", a:["Speed past","Yield and let it merge","Honk","Change lanes immediately"], c:1,
 w:"Yielding to a re-entering bus is the law where posted."},
{t:"share", q:"Hybrid and electric vehicles are a risk to pedestrians because:", a:["They accelerate faster","They are quiet","They are wider","They brake slower"], c:1,
 w:"People step out because they did not hear you coming."},
{t:"share", q:"The key to pedestrian safety at a crossing is:", a:["Honking","Eye contact","Flashing your lights","Speed"], c:1,
 w:"Eye contact between driver and pedestrian, straight from the handbook."}
];
