BANK.push(
/* ══ FREEWAY ════════════════════════════════════════════════════════════ */
{t:"freeway", q:"The three parts of a freeway entrance are:", a:["Ramp, shoulder, lane","Entrance ramp and acceleration lane","Merge lane and exit","Ramp and stop line"], c:1,
 w:"Use the acceleration lane to match traffic speed BEFORE you merge."},
{t:"freeway", q:"When entering a freeway you should:", a:["Enter slowly and speed up after","Match the speed of freeway traffic before merging","Stop at the end of the ramp","Merge immediately"], c:1,
 w:"Merging slowly forces everyone else to brake around you."},
{t:"freeway", q:"On a freeway, look ahead to where you will be in:", a:["2 to 3 seconds","5 to 8 seconds","15 to 20 seconds","30 to 40 seconds"], c:2,
 w:"The faster you go, the further ahead you must look."},
{t:"freeway", q:"On a freeway with three or more lanes each way, large trucks:", a:["Must use the far left lane","Cannot use the far left lane","Must use the middle lane only","Have no restrictions"], c:1,
 w:"They pass in the lane to the right of the far left one."},
{t:"freeway", q:"The three parts of a freeway exit are:", a:["Ramp, shoulder, stop","Deceleration lane, exit ramp, and an intersection","Merge lane and ramp","Exit lane and shoulder"], c:1,
 w:"Signal, move into the deceleration lane, THEN slow down."},
{t:"freeway", q:"When you signal to move into a deceleration lane you should:", a:["Slow down right away","Not slow down until you are in the lane","Brake hard","Stop"], c:1,
 w:"Braking in the through lane is how you get hit from behind."},
{t:"freeway", q:"Losing your sense of speed after driving fast for a while is called:", a:["Hydroplaning","Highway hypnosis","Speed adaptation or velocitization","Target fixation"], c:2,
 w:"It is why you must check the speedometer on an exit ramp."},
{t:"freeway", q:"You miss your freeway exit. You should:", a:["Reverse on the shoulder","Stop and wait for a gap","Take the next exit","Cross the grass median"], c:2,
 w:"Never stop or reverse on a freeway. Ever."},
{t:"freeway", q:"HOV lanes on provincial highways are open:", a:["Weekday rush hours only","6 a.m. to 7 p.m.","24 hours a day, 7 days a week","Weekends only"], c:2,
 w:"Always on."},
{t:"freeway", q:"How many people must normally be in a car to use a provincial HOV lane?", a:["At least 2","At least 3","At least 4","Any number"], c:0,
 w:"Driver plus at least one passenger."},
{t:"freeway", q:"Which of these may use an HOV lane with only the driver aboard?", a:["A pickup truck","A licensed taxi","A minivan","A large truck"], c:1,
 w:"Taxis, airport limos, buses, green-plate vehicles and emergency vehicles are exempt."},
{t:"freeway", q:"The striped buffer zone beside an HOV lane:", a:["Marks the shoulder","May be crossed carefully","Is illegal and unsafe to cross","Is for motorcycles"], c:2,
 w:"Wait for the dashed opening to enter or leave."},
{t:"freeway", q:"Commercial vehicles in an HOV lane must have 2+ occupants and be shorter than:", a:["5 metres","6.5 metres","8 metres","11 metres"], c:1,
 w:"6.5 metres in total length."},

/* ══ NIGHT & BAD WEATHER ════════════════════════════════════════════════ */
{t:"night", q:"Overdriving your headlights means:", a:["Using high beams in town","Driving faster than you can stop within what you can see","Leaving your lights on all day","Driving with one headlight"], c:1,
 w:"If your stopping distance is longer than your light reaches, you are driving blind."},
{t:"night", q:"Driving at the speed limit is more dangerous at night because:", a:["Your reaction time is slower","You cannot see as far ahead","Roads are more slippery","There are more drunk drivers"], c:1,
 w:"Straight from the handbook sample test: you simply cannot see as far."},
{t:"night", q:"Blinded by oncoming headlights, you should look:", a:["Straight at the lights","Down at your dashboard","Up and beyond the lights, slightly to the right","Left toward the centre line"], c:2,
 w:"Use the right edge line as your guide until they pass."},
{t:"night", q:"In fog you should:", a:["Use high beams","Use low beams and fog lights","Use parking lights","Turn off your lights"], c:1,
 w:"High beams bounce off fog straight back at you."},
{t:"night", q:"In fog you should NOT:", a:["Slow down","Increase following distance","Stop on the travelled part of the road","Use road edge markings as a guide"], c:2,
 w:"If you must stop, get completely off the road and put your flashers on."},
{t:"night", q:"Hydroplaning happens when:", a:["Your brakes get wet","Tires ride up on a film of water","Your windshield fogs","You drive through a puddle slowly"], c:1,
 w:"Tires lose contact and skim like water skis. Slow down."},
{t:"night", q:"After driving through deep water you should test your brakes by:", a:["Braking hard at 50 km/h","Braking gently at 20 km/h","Using the parking brake","Waiting for them to dry"], c:0,
 w:"Stop firmly from about 50 km/h. The car should stop straight with a firm pedal."},
{t:"night", q:"In snowy conditions you should NOT use:", a:["Low beams","Winter tires","Cruise control","Your defroster"], c:2,
 w:"Cruise control can spin the wheels on a slippery patch."},
{t:"night", q:"Winter asphalt that looks black and shiny instead of grey-white suggests:", a:["Fresh pavement","Black ice","Oil on the road","Wet leaves"], c:1,
 w:"Grey-white is normal winter asphalt. Black and glossy means ice."},
{t:"night", q:"To get out of a skid you should FIRST:", a:["Brake hard","Steer in the opposite direction","Steer where you want to go","Shift into park"], c:2,
 w:"Ease off the pedal, look and steer where you want to go, do not overcorrect."},
{t:"night", q:"In a whiteout you should:", a:["Keep driving slowly","Stop on the road and wait","Pull into a safe parking area and stay with your vehicle","Follow the tail lights ahead"], c:2,
 w:"Stay with the car, crack a window, use flashers sparingly, carry a survival kit."},
{t:"night", q:"Snow-removal vehicles display:", a:["Flashing red lights","Flashing blue lights","Flashing green lights","Steady amber lights"], c:1,
 w:"Blue flashers, visible 150 m away. Some plows have wings extending 3 m to the right."},
{t:"night", q:"Entering a tunnel on a bright day you should:", a:["Speed up","Slow down, remove sunglasses and turn on headlights","Keep sunglasses on","Use high beams"], c:1,
 w:"Your eyes need time to adjust from bright sun to dark tunnel."},
{t:"night", q:"Following distance in bad weather should be:", a:["The same as normal","Shorter","Longer than two seconds","One car length"], c:2,
 w:"Two seconds is a fair-weather minimum only."},

/* ══ EMERGENCIES ════════════════════════════════════════════════════════ */
{t:"emergencies", q:"You must report a collision to police when there are injuries or damage over:", a:["$1,000","$2,000","$5,000","$10,000"], c:2,
 w:"$5,000 or any injury. Below that, exchange information."},
{t:"emergencies", q:"After a minor collision with no injuries you must exchange:", a:["Names only","Name, address, vehicle permit and plate number, and insurance details","Insurance only","Phone numbers"], c:1,
 w:"Also take witness names and numbers."},
{t:"emergencies", q:"Vehicles are drivable after a minor collision. The rule is:", a:["Leave everything where it is","Steer it, clear it — move off the road if safe","Wait for police in the lane","Push it onto the sidewalk"], c:1,
 w:"Blocking live lanes causes a second, worse collision."},
{t:"emergencies", q:"Your brakes fail. You should first:", a:["Pull the parking brake hard","Pump the brake pedal","Shift into reverse","Turn off the engine"], c:1,
 w:"Pump first. If that fails, apply the parking brake gently but firmly while holding the release."},
{t:"emergencies", q:"Your gas pedal sticks. You should:", a:["Turn off the ignition immediately","Try to lift it with your foot, then shift to neutral and stop safely","Pull the parking brake","Steer into a ditch"], c:1,
 w:"Never reach down with your hands while moving. Do not restart afterwards."},
{t:"emergencies", q:"A front tire blows out. You should:", a:["Brake hard","Ease off the gas, steer firmly, and slow to a controlled stop","Accelerate","Turn sharply to the shoulder"], c:1,
 w:"Braking hard on a blowout can spin you."},
{t:"emergencies", q:"Your wheels drop off the pavement onto the shoulder. You should:", a:["Brake hard and steer back","Grip the wheel, ease off the gas, then steer back gently","Accelerate to get back on","Turn sharply"], c:1,
 w:"Sharp steering at speed flips you back across the road."},
{t:"emergencies", q:"Your headlights fail at night. You should:", a:["Keep driving carefully","Use hazard lights and pull off the road","Use high beams","Follow another car"], c:1,
 w:"Driving without lights at night is dangerous and illegal."},
{t:"emergencies", q:"An emergency vehicle approaches with lights and siren. You must:", a:["Speed up to clear the way","Pull as near as practical to the right curb and stop","Stop where you are","Move to the left"], c:1,
 w:"Right side, parallel, clear of intersections and ramps. Not on the shoulder of a freeway."},
{t:"emergencies", q:"You are passing a STOPPED emergency vehicle with lights flashing on a road with two lanes in your direction. You must:", a:["Stop completely","Slow down and move into the lane away from it","Maintain speed","Sound your horn"], c:1,
 w:"Slow down AND move over where there is a lane to move into."},
{t:"emergencies", q:"Failing to obey the move over law costs, on a first offence:", a:["A fine and 2 demerit points","A fine and 3 demerit points","A fine only","6 demerit points"], c:1,
 w:"3 points and a fine. Repeat offences can mean up to 6 months in jail."},
{t:"emergencies", q:"You may not follow a fire truck responding to an alarm closer than:", a:["30 metres","60 metres","100 metres","150 metres"], c:3,
 w:"150 metres. Give them room to work."},
{t:"emergencies", q:"A tow truck stopped on the highway with flashing amber lights gets:", a:["No special treatment","The same treatment as an emergency vehicle","Only a lane change","A honk"], c:1,
 w:"Slow down and move over for tow trucks too."},
{t:"emergencies", q:"In a construction zone with workers present, speeding fines are:", a:["The same","Reduced","Doubled","Waived"], c:2,
 w:"Doubled. And disobeying a traffic-control person is a separate offence."},
{t:"emergencies", q:"In a construction zone you should:", a:["Change lanes to find the fastest one","Stay in your lane and be ready for sudden stops","Speed up to clear it","Follow closely"], c:1,
 w:"Do not change lanes in a construction zone."},
{t:"emergencies", q:"You see a large animal on the road ahead. You should:", a:["Swerve around it","Sound your horn and slow down","Speed up past it","Flash your high beams and continue"], c:1,
 w:"Animals move unpredictably. Do not try to steer around one at speed."},
{t:"emergencies", q:"After hitting a large animal you should:", a:["Move it off the road","Stay in your vehicle and report it to police or the Ministry of Natural Resources","Drive away","Approach to check on it"], c:1,
 w:"Getting out on a live road is how people get hit."},
{t:"emergencies", q:"At a collision scene with injuries you should NOT:", a:["Call emergency services","Turn on hazard lights","Move injured people unless there is fire danger","Cover injured people to prevent shock"], c:2,
 w:"Moving someone with a spinal injury can be fatal."},

/* ══ LIGHTS & LINES ═════════════════════════════════════════════════════ */
{t:"lights", q:"A yellow light means:", a:["Speed up to clear the intersection","The red is about to appear — stop if you can do so safely","Stop no matter what","Proceed as if green"], c:1,
 w:"If you cannot stop safely, go through with caution."},
{t:"lights", q:"A flashing green light or a green arrow with a green light means:", a:["Yield to everyone","Oncoming traffic has a red — you may turn left, go straight or turn right","Stop and proceed","Pedestrians may cross"], c:1,
 w:"This is the advanced green. Your left turn is protected — for now."},
{t:"lights", q:"May pedestrians cross on a flashing green light?", a:["Yes, always","Only in a crosswalk","No, not unless a pedestrian signal permits it","Yes, if traffic is clear"], c:2,
 w:"The advanced green exists precisely because turning traffic is moving."},
{t:"lights", q:"A yellow ARROW after an advanced green means:", a:["Turn quickly","Do not start a new left turn — the regular green is coming","The light is broken","Stop immediately"], c:1,
 w:"Finish your turn with caution if you are already committed. Do not start one."},
{t:"lights", q:"A flashing red light means:", a:["Slow down","Come to a complete stop, then go when safe","Proceed with caution","The light is broken"], c:1,
 w:"Treat it exactly like a stop sign."},
{t:"lights", q:"A flashing yellow light means:", a:["Stop","Yield to the right","Drive through with caution","Prepare to stop"], c:2,
 w:"Caution, not a stop."},
{t:"lights", q:"A fully protected left turn means:", a:["You may turn any time","You may only turn on the green arrow, not after the through-green appears","Left turns are banned","You must yield"], c:1,
 w:"The left lane has its own signal. When it goes red, your turn is over."},
{t:"lights", q:"A white vertical bar on a dark signal is a:", a:["Broken light","Transit priority signal — yield to public transit","Pedestrian signal","Lane control signal"], c:1,
 w:"Traffic and pedestrians yield to the transit vehicle."},
{t:"lights", q:"A white walking symbol at a crosswalk means:", a:["Pedestrians may start crossing","Pedestrians must hurry","Drivers may go","Pedestrians must wait"], c:0,
 w:"And they hold the right-of-way over all vehicles while crossing."},
{t:"lights", q:"A flashing orange hand means pedestrians:", a:["May start crossing","Must not begin to cross","Must run","Have the right-of-way to start"], c:1,
 w:"Anyone already crossing keeps the right-of-way until they reach safety."},
{t:"lights", q:"Yellow lines on the pavement separate:", a:["Traffic travelling in the same direction","Traffic travelling in opposite directions","Bike lanes","Parking spaces"], c:1,
 w:"Yellow = opposing traffic. White = same direction. Memorise this one."},
{t:"lights", q:"White lines on the pavement separate:", a:["Opposing traffic","Traffic travelling in the same direction","Bus lanes only","Nothing"], c:1,
 w:"Same direction. That is why lane lines are white."},
{t:"lights", q:"A BROKEN yellow line on your side of the centre means:", a:["You may pass when it is safe","You may never pass","Passing is only allowed at night","The road is closed"], c:0,
 w:"Make sure there are enough broken lines ahead to finish the pass."},
{t:"lights", q:"A SOLID yellow line on your side of the centre means:", a:["You may pass","It is unsafe to pass — do not cross it","You must turn","The road narrows"], c:1,
 w:"Solid on your side, stay on your side."},
{t:"lights", q:"Two solid yellow lines mean:", a:["Only the left lane may pass","Neither direction may pass","A two-way left-turn lane","A bike lane"], c:1,
 w:"Nobody passes across a double solid yellow."},
{t:"lights", q:"A broken white line means:", a:["Lane changes are permitted when safe","Do not change lanes","The road ends","Bikes only"], c:0,
 w:"Broken = you may cross it. Solid = stay put."},
{t:"lights", q:"A stop line is:", a:["Two parallel white lines","A single white line painted across the road","A yellow line","A row of dots"], c:1,
 w:"It shows exactly where your bumper stops."},
{t:"lights", q:"A crosswalk is marked by:", a:["A single white line","Two parallel white lines across the road","A yellow box","Diagonal stripes"], c:1,
 w:"A pedestrian crossover adds two double lines plus a large X in each lane."},
{t:"lights", q:"Wider, more closely spaced broken lines (continuity lines) mean:", a:["A passing lane","Your lane is ending or exiting — change lanes to continue","A bike lane","A construction zone"], c:1,
 w:"If you stay in it, you are leaving the road you are on."},
{t:"lights", q:"A white arrow painted in your lane means:", a:["It is a suggestion","You may move only in the direction of the arrow","Bikes turn here","The lane ends"], c:1,
 w:"Choose your lane before you reach the arrows."},
{t:"lights", q:"A green light means you may go:", a:["Without yielding to anyone","Straight, left or right after yielding to vehicles and pedestrians already in the intersection","Only straight","Only if no one is waiting"], c:1,
 w:"Green never overrides someone already legally in the intersection."},
{t:"lights", q:"An eight-sided sign always means:", a:["Yield","Stop","School zone","Railway"], c:1,
 w:"Octagon is reserved for STOP alone — you can identify it by shape in the dark."},
{t:"lights", q:"A yellow diamond sign means:", a:["A rule you must obey","A hazard or change in the road ahead","Road work","A destination"], c:1,
 w:"Yellow diamond = warning. Orange diamond = temporary road work."},
{t:"lights", q:"A five-sided fluorescent yellow-green sign means:", a:["Construction","Railway","School zone or school crossing","Hospital"], c:2,
 w:"Pentagon plus that unmistakable green-yellow = kids."},
{t:"lights", q:"A green circle on a regulatory sign means:", a:["The activity shown is banned","You may or must do the activity shown","Warning","Go faster"], c:1,
 w:"Green circle = allowed. Red circle with a slash = banned."},
{t:"lights", q:"An orange sign means:", a:["A permanent rule","A temporary condition such as road work","A tourist attraction","A hospital"], c:1,
 w:"Orange is always temporary."},
{t:"lights", q:"Green rectangular signs with white letters give you:", a:["Warnings","Rules","Directions, distances and destinations","Service information"], c:2,
 w:"Green = direction. Blue = services. Brown = parks and recreation."},
{t:"lights", q:"An X-shaped red and white sign means:", a:["Dead end","Railway crossing","School crossing","Intersection ahead"], c:1,
 w:"The crossbuck. Slow, look both ways, listen."}
);
