/* ── Right-of-way scenarios ──────────────────────────────────────────────
   Each is drawn as a plan view. `cars` are placed on approach legs:
   n/s/e/w = which leg they sit on, dir = where they are going.          */
const SCENARIOS = [
 {id:"s1", kind:"allway", q:"All four arrived at the all-way stop. YOU (blue) stopped first. Who goes?",
  cars:[{leg:"s",go:"n",you:true},{leg:"w",go:"e"},{leg:"n",go:"s"},{leg:"e",go:"w"}],
  a:["You — first to stop goes first","The car on your right","The car going straight","Everybody at once"], c:0,
  w:"At an all-way stop it is simply first to come to a complete stop, first to go."},
 {id:"s2", kind:"allway", q:"You (blue) and the silver car stopped at exactly the same moment. Who goes first?",
  cars:[{leg:"s",go:"n",you:true},{leg:"e",go:"w"}],
  a:["You","The silver car on your right","Whoever signals first","The one going straight"], c:1,
  w:"Tie? The vehicle on the RIGHT goes first. The silver car is to your right."},
 {id:"s3", kind:"none", q:"No signs, no lights. You (blue) and the silver car reach it together. Who yields?",
  cars:[{leg:"s",go:"n",you:true},{leg:"e",go:"w"}],
  a:["The silver car yields to you","You yield to the silver car","Neither — go together","The faster car yields"], c:1,
  w:"Uncontrolled intersection: the driver on the LEFT yields. The silver car is on your right, so you wait."},
 {id:"s4", kind:"light", light:"green", q:"You (blue) have a green light and want to turn LEFT. A silver car is coming straight at you.",
  cars:[{leg:"s",go:"w",you:true},{leg:"n",go:"s"}],
  a:["You go — you have a green","You wait for the silver car to clear","The silver car must stop for you","Whoever is faster"], c:1,
  w:"A green light does NOT give a left-turning driver the right-of-way over oncoming traffic."},
 {id:"s5", kind:"light", t:"lights", light:"advgreen", q:"You (blue) face a FLASHING GREEN and want to turn left. What does it mean?",
  cars:[{leg:"s",go:"w",you:true}],
  a:["Yield to everyone","Oncoming traffic has a red light — your left turn is protected","Stop first","Pedestrians have priority"], c:1,
  w:"Advanced green. Oncoming traffic is stopped, so you may turn left, go straight or turn right."},
 {id:"s6", kind:"light", t:"turns", light:"red", q:"You (blue) face a red light and want to turn RIGHT. There is no sign prohibiting it.",
  cars:[{leg:"s",go:"e",you:true}],
  a:["Turn without stopping if clear","Come to a complete stop, then turn when clear","Wait for green","Right turns on red are illegal"], c:1,
  w:"Complete stop first, then yield to pedestrians and traffic, then go."},
 {id:"s7", kind:"light", t:"lights", light:"dark", q:"The traffic lights are completely dead. Four cars arrive. What do you do?",
  cars:[{leg:"s",go:"n",you:true},{leg:"w",go:"e"},{leg:"n",go:"s"}],
  a:["Treat it as a green","Treat it as an all-way stop","Drive through carefully","Wait for police"], c:1,
  w:"A blank signal is an all-way stop. Yield to anyone already in it and to the vehicle on your right."},
 {id:"s8", kind:"driveway", q:"You are pulling out of a driveway. A pedestrian is on the sidewalk and a car is on the road.",
  cars:[{leg:"s",go:"n",you:true},{leg:"w",go:"e"}], ped:true,
  a:["Yield to the car only","Yield to the pedestrian only","Yield to both","You have right-of-way leaving a driveway"], c:2,
  w:"Leaving a private driveway you yield to everything — vehicles on the road AND people on the sidewalk."},
 {id:"s9", kind:"pxo", t:"share", q:"A pedestrian has crossed to the far side of a pedestrian crossover but is still on the road. You:",
  cars:[{leg:"s",go:"n",you:true}], ped:true,
  a:["Go once they pass your lane","Wait until they are completely across the road","Go if they wave you on","Slow and proceed"], c:1,
  w:"Completely across. Not past your lane — off the road entirely."},
 {id:"s10", kind:"roundabout", q:"You are at the yield line of a roundabout. A car is already circulating to your left.",
  cars:[{leg:"s",go:"n",you:true}],
  a:["Enter — you have right-of-way","Yield to the circulating car","Enter beside it","Sound your horn"], c:1,
  w:"Traffic already in the roundabout always has the right-of-way. Look LEFT."},
 {id:"s11", kind:"allway", q:"You (blue) want to turn LEFT. The car opposite you stopped at the same time and is going straight.",
  cars:[{leg:"s",go:"w",you:true},{leg:"n",go:"s"}],
  a:["You turn first","The straight-through car goes first","Both go together","Whoever signals first"], c:1,
  w:"When two vehicles face each other, the one going straight goes before the one turning left."},
 {id:"s12", kind:"schoolbus", t:"share", q:"A school bus ahead of you has its upper red lights flashing. There is no median.",
  cars:[{leg:"s",go:"n",you:true}],
  a:["Pass slowly on the left","Stop at least 20 metres back","Stop right behind it","Sound your horn and pass"], c:1,
  w:"20 metres back, and you stay there until the lights stop and the arm folds in."},
 {id:"s13", kind:"schoolbus", median:true, t:"share", q:"You are approaching a stopped school bus with red lights flashing from the OPPOSITE direction. The road has a raised median.",
  cars:[{leg:"n",go:"s",you:true}],
  a:["You must stop","You may continue with caution","You must stop 20 m back","Reverse away"], c:1,
  w:"A physical median means only traffic behind the bus must stop. Still slow down."},
 {id:"s14", kind:"light", queue:true, t:"lights", light:"green", q:"You have a green light but traffic ahead is backed up across the intersection.",
  cars:[{leg:"s",go:"n",you:true}],
  a:["Enter — you have the green","Wait until you can clear the far side","Enter and wait in the middle","Turn right instead"], c:1,
  w:"Never block an intersection. Green means go only if there is somewhere to go."},
 {id:"s15", kind:"emergency", t:"emergencies", q:"An ambulance with lights and siren approaches from behind on a two-lane road.",
  cars:[{leg:"s",go:"n",you:true}],
  a:["Speed up to get out of the way","Stop where you are","Pull as far right as safe, parallel, and stop","Move to the left"], c:2,
  w:"Right side, parallel to the road, clear of intersections. Then wait for more emergency vehicles."},
 {id:"s16", kind:"none", q:"You reach an uncontrolled intersection first, well before the car on your right. You:",
  cars:[{leg:"s",go:"n",you:true},{leg:"e",go:"w"}],
  a:["Must still yield to the right","May proceed — you arrived first","Must stop and wait","Must sound your horn"], c:1,
  w:"Arriving clearly first gives you priority. The right-hand rule only settles ties."}
];

/* ── Numbers that show up constantly on the G1 ─────────────────────────── */
const NUMBERS = [
 {q:"Stop this far behind a school bus with red lights flashing", v:20, u:"m", opts:[5,10,20,30], t:"share", w:"20 metres gives kids room to cross."},
 {q:"Stop at least this far from the nearest rail when a train is coming", v:5, u:"m", opts:[3,5,10,15], t:"intersections", w:"5 metres from the nearest rail or gate."},
 {q:"Do not park within this distance of a fire hydrant", v:3, u:"m", opts:[1,3,6,9], t:"parking", w:"3 metres."},
 {q:"Do not park within this distance of an intersection with traffic lights", v:15, u:"m", opts:[3,9,15,30], t:"parking", w:"15 m at a signalised intersection."},
 {q:"Do not park within this distance of an UNCONTROLLED intersection", v:9, u:"m", opts:[3,6,9,15], t:"parking", w:"9 metres."},
 {q:"Do not park within this distance of the nearest rail of a railway crossing", v:15, u:"m", opts:[5,9,15,30], t:"parking", w:"15 metres."},
 {q:"Do not park within this distance of a bridge", v:100, u:"m", opts:[15,30,60,100], t:"parking", w:"100 metres on or near a bridge."},
 {q:"Do not park within this distance of a public building entrance", v:6, u:"m", opts:[3,6,9,15], t:"parking", w:"6 metres."},
 {q:"Minimum passing distance when overtaking a cyclist", v:1, u:"m", opts:[0.5,1,2,3], t:"share", w:"1 metre where practical."},
 {q:"Stay at least this far behind a streetcar's rear doors at a stop", v:2, u:"m", opts:[1,2,5,10], t:"share", w:"2 metres."},
 {q:"Switch from high to low beams within this distance of an oncoming vehicle", v:150, u:"m", opts:[60,100,150,300], t:"ready", w:"150 metres."},
 {q:"Use low beams when following a vehicle within this distance", v:60, u:"m", opts:[30,60,100,150], t:"ready", w:"60 metres."},
 {q:"Your headlights must shine white light at least this far ahead", v:150, u:"m", opts:[60,110,150,200], t:"ready", w:"150 m of light; objects visible at 110 m."},
 {q:"Do not pass within this distance of a pedestrian crossover", v:30, u:"m", opts:[10,15,30,50], t:"positions", w:"30 metres."},
 {q:"Do not pass left of centre within this distance of a bridge or tunnel", v:30, u:"m", opts:[15,30,50,100], t:"positions", w:"30 metres."},
 {q:"Do not follow a responding fire vehicle closer than", v:150, u:"m", opts:[60,100,150,300], t:"emergencies", w:"150 metres."},
 {q:"Before a U-turn you must see this far in both directions", v:150, u:"m", opts:[50,100,150,200], t:"turns", w:"150 metres each way."},
 {q:"Park only where you have a clear view this far in both directions", v:125, u:"m", opts:[75,100,125,200], t:"parking", w:"125 metres."},
 {q:"Finish parallel parking within this distance of the curb", v:30, u:"cm", opts:[10,30,60,100], t:"parking", w:"About 30 centimetres."},
 {q:"A correctly installed child car seat moves no more than", v:2.5, u:"cm", opts:[1,2.5,5,10], t:"ready", w:"2.5 cm at the belt path."},
 {q:"Default speed limit in a city, town or village with no sign posted", v:50, u:"km/h", opts:[40,50,60,80], t:"along", w:"50 km/h."},
 {q:"Default speed limit outside a built-up area with no sign posted", v:80, u:"km/h", opts:[60,70,80,100], t:"along", w:"80 km/h."},
 {q:"A slow-moving vehicle sign means the vehicle travels at or below", v:40, u:"km/h", opts:[20,40,60,80], t:"share", w:"40 km/h or less."},
 {q:"Minimum following distance behind the vehicle ahead", v:2, u:"seconds", opts:[1,2,3,4], t:"along", w:"2 seconds in good conditions."},
 {q:"Check your mirrors about every", v:5, u:"seconds", opts:[5,15,30,60], t:"along", w:"Every 5 seconds."},
 {q:"On a freeway, look ahead to where you will be in about", v:20, u:"seconds", opts:[5,10,20,40], t:"freeway", w:"15 to 20 seconds ahead."},
 {q:"Turn off your engine if you will be parked longer than", v:10, u:"seconds", opts:[10,30,60,300], t:"emergencies", w:"10 seconds."},
 {q:"You must report a collision to police at damage above", v:5000, u:"$", opts:[1000,2000,5000,10000], t:"emergencies", w:"$5,000 or any injury."},
 {q:"A train under full emergency braking may need up to", v:2, u:"km", opts:[0.5,1,2,5], t:"intersections", w:"Up to 2 kilometres."},
 {q:"Arrive at least this early for a road test", v:30, u:"minutes", opts:[10,15,30,60], t:"licence", w:"30 minutes."},
 {q:"Minimum wait between road test attempts", v:10, u:"days", opts:[3,10,30,60], t:"licence", w:"10 days."},
 {q:"Minimum time you must hold a G1 with driver education", v:8, u:"months", opts:[4,8,12,18], t:"licence", w:"8 months with an approved course, 12 without."},
 {q:"Minimum accompanying-driver experience for a G1 driver", v:4, u:"years", opts:[1,2,4,10], t:"licence", w:"4 years."},
 {q:"Demerit points stay on your record for", v:2, u:"years", opts:[1,2,3,5], t:"penalties", w:"2 years from the date of the offence."},
 {q:"New Ontario residents must get an Ontario licence within", v:60, u:"days", opts:[30,60,90,180], t:"licence", w:"60 days."},
 {q:"Total hours in an approved Beginner Driver Education course", v:40, u:"hours", opts:[20,30,40,60], t:"licence", w:"40 hours: 20 classroom, 10 in-car, 10 flexible."},
 {q:"Sit high enough to see the road this far in front of your vehicle", v:4, u:"m", opts:[2,4,8,12], t:"ready", w:"4 metres."},
 {q:"Snow plow flashing blue lights are visible from", v:150, u:"m", opts:[50,100,150,300], t:"night", w:"150 metres. Never pass a working plow."}
];
